Added testcases for OrangeHRM
arminazizyan99/OrangeHRM-e2e-testing pull request #1
Opened 2023-12-21 11:49 UTC by arminazizyan99

Checked scrollbar functionality, verified that an admin user can successfully add a new employee by entering the required information, ensured that the new employee is saved in the system and their login credentials are valid, stored the newly created employee data in the shared context object. Tests are isolated via clean up of shared object.

2023-12-28 12:03 UTC, Mohammad-Nada-Op requested changes

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress.config.ts
> +    user: { username: "Admin", password: "admin123" },
for security purposes, use .env. file

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/pages/EmployeePage.ts
> +        const EmployeeData = {
can we make dynamic, using pass params instead of magic string

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/support/commands.ts
> +Cypress.Commands.add("hideCommandLogRequest", (pageUrl) => {
Can you add a description for the function, like jsdoc

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/add-new-employee.cy.ts
> +            const id = UserData.userId
Use AAA design pattern.

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/add-new-employee.cy.ts
> +            cy.intercept("DELETE", EmployeePage.deleteUserApiUrl).as("delete")
Is deleting user within the test scope? if not let do this step via api not UI

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/password-fields.cy.ts
> +                if (cachedPassword === null) {
!cachedPassword is clearer

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress.config.ts
> +        setMyUser: (param1) => {
- you should not explicitly return a value from a setter method
- Suggestion: All user data's setter should add a key value to the userData object, for example (user.userId = userId)

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress.config.ts
> +        setValidPassword: (password) => {
this is a set method, should only do one thing(set value). we should not check the password.length

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            EmployeePage.fillInEmployeeDetailsFields(UserData.firstName, UserData.middleName, UserData.lastName, UserData.userId, UserData.userName, UserData.userStatus)
EmployeePage is an object not class, should start with small letter

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/pages/EmployeePage.ts
> +    fillInEmployeeDetailsFields(firstName: string, middleName: string, lastName: string, userId: string, userName: string, userStatus: status) {
Using Destructuring assignment will be much clearer

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +                const number = response.body.data.empNumber
I would like to see safety check

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            cy.get('@EmpNumber').then((number) => {
we can do it with one line

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            cy.wait("@addEmployee").its('response').then((response) => {
use destructure

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            cy.get(EmployeePage.passwordField).each((passw) => {
no need for curly braces, you can do it with one line

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            cy.get(EmployeePage.searchByName).first().type(UserData.firstName)
void using first and last, we can do it by the selector

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            cy.get('@EmpNumber').then((number) => {
The same, one line 👍

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/password-validation.cy.ts
> +                if (cachedPassword === null) {
you can use `if (!cachedPassword)`

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/password-validation.cy.ts
> +            cy.get(EmployeePage.searchByName).first().type(UserData.firstName)
the same for .first and .last

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/password-validation.cy.ts
> +                if (cachedPassword === null) {
The same

2023-12-28 12:03 UTC, Mohammad-Nada-Op commented on cypress/pages/PasswordPage.ts
> +            cy.wait("@passwordAPI").its('response')
Can we move cy.wait( out side the if's scope?

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +        cy.task('resetEmpNumber')
can we refactor the block to delete the Emp then use one fun(task) to reset all saved data?

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            cy.wait("@addEmployee").its('response').then((response) => {
Use destructure params
cy.wait("@addEmployee").then(({ response } )

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +                const { data } = response.body;
I would like to see safety check

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/new-employee.cy.ts
> +            cy.wait("@addEmployee").its('response')
I guess this unintentional

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/e2e/tests/password-validation.cy.ts
> +            if (passwordPage.checkifValid(data.Password[passwordKey])) {
move passwordPage.checkifValid(data.Password[passwordKey] into const

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/pages/employeePage.ts
> +class employeePage {
Class name always start with capital

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/pages/employeePage.ts
> +        cy.get(this.userIDField).eq(4).type(userId);
since we are using userIDField selector with .eq(4)  always, we can update the selector to get the 4th element directly

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/pages/employeePage.ts
> +        cy.get(this.userNameField).eq(5).invoke("val").then((value) => {
The same for eq

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/pages/homePage.ts
> +class homePage {
should start with capital letter

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/pages/loginPage.ts
> +    cy.get(this.userNameField).should("have.value", "").type(username)
why we do assertion inside pageObject?

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/pages/passwordPage.ts
> +        if (password.length >= 7 && /\d/.test(password)) {
- put the condition value inside const 
- Use ternary if statement

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/src/models.ts
> +  value = 'val'
for consistency, use single or double quotation everywhere

2024-01-08 10:16 UTC, Mohammad-Nada-Op commented on cypress/support/e2e.ts
> +      loginPage.login();
Can we do the login via api?

2024-01-10 12:23 UTC, arminazizyan99 commented on cypress/support/e2e.ts
> +      loginPage.login();
I attempted to log in via the API, but the required token wasn't directly accessible in the response code. As a result, I'll opt for logging in through the website instead of using the API.

2024-02-06 11:24 UTC, merged